# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import formulator.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['field', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(help_text='Verbose field name and form label ', max_length=200)),
                ('field_id', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=formulator.utils.slugify, unique_with=('form',))),
                ('field_type', models.CharField(choices=[(b'formulator.fields.ShortAnswer', b'Short Answer'), (b'formulator.fields.Paragraph', b'Paragraph'), (b'formulator.fields.MultipleChoice', b'Multiple Choice'), (b'formulator.fields.Checkboxes', b'Checkboxes'), (b'formulator.fields.DropDown', b'Dropdown'), (b'formulator.fields.SingleCheckbox', b'Single Checkbox'), (b'formulator.fields.Date', b'Date'), (b'formulator.fields.DateTime', b'Date & Time'), (b'formulator.fields.Time', b'Time'), (b'formulator.fields.Number', b'Number'), (b'formulator.fields.Slug', b'Slug'), (b'formulator.fields.Email', b'Email')], max_length=100)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('help_text', models.TextField(blank=True, help_text="An optional string to use as 'help text' for this Field.")),
                ('initial', models.CharField(blank=True, help_text='Form field initial attribute', max_length=200)),
                ('widget', models.CharField(blank=True, help_text='Widget class', max_length=100)),
                ('is_hidden', models.BooleanField(default=False, help_text='If the field is hidden.')),
            ],
            options={
                'ordering': ['form', 'position'],
            },
        ),
        migrations.CreateModel(
            name='FieldAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_attributes', to='formulator.Field')),
            ],
        ),
        migrations.CreateModel(
            name='FieldSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['form', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Form type', max_length=100)),
                ('form_name', models.CharField(blank=True, max_length=100)),
                ('form_action', models.CharField(blank=True, max_length=250)),
                ('form_method', models.IntegerField(choices=[(0, 'GET'), (1, 'POST')], default=1)),
                ('form_id', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=formulator.utils.slugify)),
                ('form_class', models.CharField(blank=True, max_length=250)),
                ('form_accept_charset', models.CharField(blank=True, max_length=100)),
                ('form_autocomplete', models.BooleanField(default=False)),
                ('form_novalidate', models.BooleanField(default=False)),
                ('form_enctype', models.IntegerField(choices=[(0, 'application/x-www-form-urlencoded'), (1, 'multipart/form-data'), (2, 'text/plain')], default=0)),
                ('form_target', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_attributes', to='formulator.Field')),
            ],
        ),
        migrations.AddField(
            model_name='fieldset',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldsets', to='formulator.Form'),
        ),
        migrations.AddField(
            model_name='field',
            name='fieldset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formulator.FieldSet'),
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formulator.Form'),
        ),
        migrations.AddField(
            model_name='choice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='formulator.Field'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetattribute',
            unique_together=set([('field', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldset',
            unique_together=set([('form', 'position'), ('form', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldattribute',
            unique_together=set([('field', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set([('field_id', 'fieldset'), ('field_id', 'form')]),
        ),
    ]
