# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[(b'floppyforms.fields.Field', b'Field'), (b'floppyforms.fields.CharField', b'CharField'), (b'floppyforms.fields.IntegerField', b'IntegerField'), (b'floppyforms.fields.DateField', b'DateField'), (b'floppyforms.fields.TimeField', b'TimeField'), (b'floppyforms.fields.DateTimeField', b'DateTimeField'), (b'floppyforms.fields.EmailField', b'EmailField'), (b'floppyforms.fields.FileField', b'FileField'), (b'floppyforms.fields.ImageField', b'ImageField'), (b'floppyforms.fields.URLField', b'URLField'), (b'floppyforms.fields.BooleanField', b'BooleanField'), (b'floppyforms.fields.NullBooleanField', b'NullBooleanField'), (b'floppyforms.fields.ChoiceField', b'ChoiceField'), (b'floppyforms.fields.MultipleChoiceField', b'MultipleChoiceField'), (b'floppyforms.fields.FloatField', b'FloatField'), (b'floppyforms.fields.DecimalField', b'DecimalField'), (b'floppyforms.fields.SlugField', b'SlugField'), (b'floppyforms.fields.RegexField', b'RegexField'), (b'floppyforms.fields.GenericIPAddressField', b'GenericIPAddressField'), (b'floppyforms.fields.TypedChoiceField', b'TypedChoiceField'), (b'floppyforms.fields.FilePathField', b'FilePathField'), (b'floppyforms.fields.TypedMultipleChoiceField', b'TypedMultipleChoiceField'), (b'floppyforms.fields.ComboField', b'ComboField'), (b'floppyforms.fields.MultiValueField', b'MultiValueField'), (b'floppyforms.fields.SplitDateTimeField', b'SplitDateTimeField')], max_length=100),
        ),
        migrations.AlterOrderWithRespectTo(
            name='field',
            order_with_respect_to=None,
        ),
    ]
