# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['form', 'position']},
        ),
        migrations.AlterModelOptions(
            name='fieldset',
            options={'ordering': ['form', 'position']},
        ),
        migrations.AlterField(
            model_name='field',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='fieldset',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
