# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0002_auto_20151218_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['field', 'position']},
        ),
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set([]),
        ),
    ]
