# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:04
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import formulator.models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0003_auto_20160223_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', sep='_', slugify=formulator.models.custom_slugify, unique_with=('form',)),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[(b'floppyforms.fields.Field', b'Field'), (b'floppyforms.fields.CharField', b'CharField'), (b'floppyforms.fields.IntegerField', b'IntegerField'), (b'floppyforms.fields.DateField', b'DateField'), (b'floppyforms.fields.TimeField', b'TimeField'), (b'floppyforms.fields.DateTimeField', b'DateTimeField'), (b'floppyforms.fields.EmailField', b'EmailField'), (b'floppyforms.fields.FileField', b'FileField'), (b'floppyforms.fields.ImageField', b'ImageField'), (b'floppyforms.fields.URLField', b'URLField'), (b'floppyforms.fields.BooleanField', b'BooleanField'), (b'floppyforms.fields.NullBooleanField', b'NullBooleanField'), (b'floppyforms.fields.ChoiceField', b'ChoiceField'), (b'floppyforms.fields.MultipleChoiceField', b'MultipleChoiceField'), (b'floppyforms.fields.FloatField', b'FloatField'), (b'floppyforms.fields.DecimalField', b'DecimalField'), (b'floppyforms.fields.SlugField', b'SlugField'), (b'floppyforms.fields.RegexField', b'RegexField'), (b'floppyforms.fields.GenericIPAddressField', b'GenericIPAddressField'), (b'floppyforms.fields.TypedChoiceField', b'TypedChoiceField'), (b'floppyforms.fields.FilePathField', b'FilePathField'), (b'floppyforms.fields.TypedMultipleChoiceField', b'TypedMultipleChoiceField'), (b'floppyforms.fields.ComboField', b'ComboField'), (b'floppyforms.fields.MultiValueField', b'MultiValueField'), (b'floppyforms.fields.SplitDateTimeField', b'SplitDateTimeField'), (b'submitto.utils.fields.CountryChoiceField', b'CountryField'), (b'vies.fields.VATINField', b'VATField')], max_length=100),
        ),
    ]
