# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:27
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import formulator.models


class Migration(migrations.Migration):

    dependencies = [
        ('formulator', '0004_auto_20160309_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='name',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='label', sep='_', slugify=formulator.models.custom_slugify, unique_with=('form',)),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[(b'submitto.contrib.forms.fields.ShortAnswer', b'Short Answer'), (b'submitto.contrib.forms.fields.Paragraph', b'Paragraph'), (b'submitto.contrib.forms.fields.MultipleChoice', b'Multiple Choice'), (b'submitto.contrib.forms.fields.Checkboxes', b'Checkboxes'), (b'submitto.contrib.forms.fields.DropDown', b'Dropdown'), (b'submitto.contrib.forms.fields.SingleCheckbox', b'Single Checkbox'), (b'submitto.contrib.forms.fields.Date', b'Date'), (b'submitto.contrib.forms.fields.DateTime', b'Date & Time'), (b'submitto.contrib.forms.fields.Time', b'Time'), (b'submitto.contrib.forms.fields.Number', b'Number'), (b'submitto.contrib.forms.fields.Slug', b'Slug'), (b'submitto.contrib.forms.fields.Email', b'Email'), (b'submitto.contrib.forms.fields.CustomVATINField', b'VAT'), (b'submitto.contrib.forms.fields.CustomCountryField', b'Country select')], max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='initial',
            field=models.CharField(blank=True, help_text="A value to use in this Field's initial display. This value\n                       is *not* used as a fallback if data isn't given. ", max_length=200),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.CharField(help_text='A verbose name for this field, for use in displaying this\n                       field in a form. By default, Django will use a "pretty"\n                       version of the form field name, if the Field is part of a\n                       Form. ', max_length=200),
        ),
        migrations.AlterField(
            model_name='field',
            name='widget',
            field=models.CharField(blank=True, choices=[(b'floppyforms.widgets.TextInput', b'TextInput'), (b'floppyforms.widgets.PasswordInput', b'PasswordInput'), (b'floppyforms.widgets.HiddenInput', b'HiddenInput'), (b'floppyforms.widgets.ClearableFileInput', b'ClearableFileInput'), (b'floppyforms.widgets.FileInput', b'FileInput'), (b'floppyforms.widgets.DateInput', b'DateInput'), (b'floppyforms.widgets.DateTimeInput', b'DateTimeInput'), (b'floppyforms.widgets.TimeInput', b'TimeInput'), (b'floppyforms.widgets.Textarea', b'Textarea'), (b'floppyforms.widgets.CheckboxInput', b'CheckboxInput'), (b'floppyforms.widgets.Select', b'Select'), (b'floppyforms.widgets.NullBooleanSelect', b'NullBooleanSelect'), (b'floppyforms.widgets.SelectMultiple', b'SelectMultiple'), (b'floppyforms.widgets.RadioSelect', b'RadioSelect'), (b'floppyforms.widgets.CheckboxSelectMultiple', b'CheckboxSelectMultiple'), (b'floppyforms.widgets.SearchInput', b'SearchInput'), (b'floppyforms.widgets.RangeInput', b'RangeInput'), (b'floppyforms.widgets.ColorInput', b'ColorInput'), (b'floppyforms.widgets.EmailInput', b'EmailInput'), (b'floppyforms.widgets.URLInput', b'URLInput'), (b'floppyforms.widgets.PhoneNumberInput', b'PhoneNumberInput'), (b'floppyforms.widgets.NumberInput', b'NumberInput'), (b'floppyforms.widgets.IPAddressInput', b'IPAddressInput'), (b'floppyforms.widgets.MultiWidget', b'MultiWidget'), (b'floppyforms.widgets.Widget', b'Widget'), (b'floppyforms.widgets.SplitDateTimeWidget', b'SplitDateTimeWidget'), (b'floppyforms.widgets.SplitHiddenDateTimeWidget', b'SplitHiddenDateTimeWidget'), (b'floppyforms.widgets.MultipleHiddenInput', b'MultipleHiddenInput'), (b'floppyforms.widgets.SelectDateWidget', b'SelectDateWidget'), (b'floppyforms.widgets.SlugInput', b'SlugInput')], help_text="A Widget class, or instance of a Widget class, that should\n                       be used for this Field when displaying it. Each Field has a\n                       default Widget that it'll use if you don't specify this. In\n                       most cases, the default widget is TextInput.", max_length=100),
        ),
    ]
